version: '3'
services:
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/bot
  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx_default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/bot
    ports:
      - ${PORT}:80
    restart: always
    depends_on:
      - php